DMS_id: TCRG1_MOUSE_Tsuboyama_2023_1E0L
cv_scheme: null
dataset: ???
defaults:
- kernel: kermut
- data: paths
- _self_
- override hydra/job_logging: disabled
hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
optim:
  lr: 0.1
  n_steps: 2
  progress_bar: false
overwrite: false
preference_sampling_strategy: uniform_10
preferential: false
progress_bar: true
seed: 2024
single:
  id: null
  use_id: false
target_seq: GATAVSEWTEYKTADGKTYYYNNRTLESTWEKPQELK
use_gpu: false
